# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except ImportError:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class SequenceSetUtils(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login',
            service_ver='release',
            async_job_check_time_ms=100, async_job_check_time_scale_percent=150, 
            async_job_check_max_time_ms=300000):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = service_ver
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc,
            async_job_check_time_ms=async_job_check_time_ms,
            async_job_check_time_scale_percent=async_job_check_time_scale_percent,
            async_job_check_max_time_ms=async_job_check_max_time_ms)

    def buildFromFasta(self, params, context=None):
        """
        :param params: instance of type "FastaInputParams" (ws_name -
           workspace name path - path to fasta in the workspace) ->
           structure: parameter "ws_name" of String, parameter "path" of
           String
        :returns: instance of type "SequenceSetOutputParams" (SequenceSet_ref
           - handle to the new SequenceSet object) -> structure: parameter
           "SequenceSet_ref" of String
        """
        return self._client.run_job('SequenceSetUtils.buildFromFasta',
                                    [params], self._service_ver, context)

    def buildFromLocations(self, params, context=None):
        """
        :param params: instance of type "LocationInputParams" (ws_name -
           workspace name seqlocations - list of sequence locations) ->
           structure: parameter "ws_name" of String, parameter "seqlocations"
           of list of type "sequence_location" (genome_ref - handle to genome
           genlocations - list of locations in the genome to build a single
           sequence from, usually length 1) -> structure: parameter
           "genome_ref" of String, parameter "genlocations" of list of tuple
           of size 4: type "Contig_id" (Insert your typespec information
           here.), Long, type "orientation", Long
        :returns: instance of type "SequenceSetOutputParams" (SequenceSet_ref
           - handle to the new SequenceSet object) -> structure: parameter
           "SequenceSet_ref" of String
        """
        return self._client.run_job('SequenceSetUtils.buildFromLocations',
                                    [params], self._service_ver, context)

    def buildFromFeatureSet(self, params, context=None):
        """
        :param params: instance of type "FeatureSetInputParams" (ws_name -
           workspace name FeatureSet_ref - handle to input feature set
           genome_ref - handle to genome to extract features from
           upstream_length - length of region upstream of features to extract
           sequences from) -> structure: parameter "ws_name" of String,
           parameter "FeatureSet_ref" of String, parameter "genome_ref" of
           String, parameter "upstream_length" of Long
        :returns: instance of type "SequenceSetOutputParams" (SequenceSet_ref
           - handle to the new SequenceSet object) -> structure: parameter
           "SequenceSet_ref" of String
        """
        return self._client.run_job('SequenceSetUtils.buildFromFeatureSet',
                                    [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.run_job('SequenceSetUtils.status',
                                    [], self._service_ver, context)
